# Generated by Django 2.2.17 on 2020-11-06 08:13

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    stdimage.models.StdImageField(
                        height_field="height",
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="File of the image",
                        width_field="width",
                    ),
                ),
                ("width", models.PositiveIntegerField(verbose_name="Width of image")),
                ("height", models.PositiveIntegerField(verbose_name="Height of image")),
                ("size", models.PositiveIntegerField(verbose_name="Size of the image file")),
                ("extension", models.CharField(max_length=8, verbose_name="Extension of the image file")),
            ],
        ),
    ]
